### ISSUE TITLE
Latest update causes a crash at launch

### ISSUE THREAD

**Issue by carlo-rigacci** [blat-blatnik/TFC-Quick-Pockets#11]
[crash-2021-02-21_13.15.25-client.txt](https://github.com/blat-blatnik/TFC-Quick-Pockets/files/6017671/crash-2021-02-21_13.15.25-client.txt)

I've uploaded the crash report above. I downgraded to the version before this one and I was launching the game fine again. I can upload my mod list if necessary.

**Comment by blat-blatnik** [comment]
Very strange. It's caused by:

```java
public static int HOTBAR_SIZE = InventoryPlayer.getHotbarSize();
```

Apparently `InventoryPlayer.getHotbarSize()` doesn't exist.. but this isn't a new change, this line looked like this for quite a few versions now without any issue. And this is a vanilla method, so it shouldn't have changed in between the TFC+ versions.

Still, if I hardcode it to:

```java
public static int HOTBAR_SIZE = 9;
```

the crash goes away.
